version: '3.8'
services:
    test-db:
        image: postgres:13
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: testtest
            POSTGRES_DB: event-reservation
        networks:
            - mylocal
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel debug --requirepass ""
        volumes:
            - cache:/data

    test-cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6380:6379'
        command: redis-server --save 20 1 --loglevel debug --requirepass ""
        volumes:
            - test-cache:/data
volumes:
    cache:
        driver: local
    test-cache:
        driver: local
networks:
    mylocal:
